[theme]
primaryColor = "#087f5b"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7F9"
textColor = "#12304A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
